### ISSUE TITLE
Can I just using css class don't set attr  background-image to element

### ISSUE THREAD

**Issue by cycold** [hilongjw/vue-lazyload#143]
```
When Using `background-image` type, 
Is there a way to don't set attr `background-image` to bind element, 
just add class name `loading` `error` to the element, 
Because I just using css class display background-image,
 if set `background-image` to this element that can cover my background-image in css
```

```
<div class="_img" v-lazy:background-image="user.userPic">
```

When `user.userPic` == undefined or "" , I got 

```
<div class="_img" lazy="error" style="background-image: url(/static/images/default-product.png);"></div>
```
But My expected: 

```
<div class="_img" lazy="error"></div>
```

Because `/static/images/default-product.png` is a global src when error,
Here I hope set local background-image by css.

I know that can use imgObj bind local error, loading img But I really can just using css class

```
imgObj: {
          src: this.user.userPic,
          error: '/static/images/avatar.png',
          loading: '/static/images/avatar.png'
}
```

```css
._img {
          display: inline-block;
          width: 70px;
          height: 70px;
          border: 2px solid #fff;
          border-radius: 150%;
          margin-bottom: 7px;
          background-repeat: no-repeat;
          background-size: 110%;
          background-position: center;
          background-image: url(/static/images/avatar.png);
          // background: no-repeat center/110% url(/static/images/avatar.png);
          img { width: 100%; height: 100%; }
        }
        ._img[lazy=loading],  ._img[lazy=error]{
          background: no-repeat center/110% url(/static/images/avatar.png);
        }
```

> sorry, poor English
