### ISSUE TITLE
max-width:100% v-lazy失效

### ISSUE THREAD

**Issue by flybbjcs70** [hilongjw/vue-lazyload#310]
```css
.u-response{
  max-width:100%;display:block;
    
}
.u-response-w{
  max-width:100%;display:block;
  width:100%
    
}
```
如果只有max-width:100%;没有width，v-lazy就会失效，图片直接显示了。

link:
[https://jsbin.com/qitakizido/edit?html,css,js,output](https://jsbin.com/qitakizido/edit?html,css,js,output)
