### ISSUE TITLE
Detect when image is loaded

### ISSUE THREAD

**Issue by rocchidavide** [hilongjw/vue-lazyload#368]
Instead of show the image specified in `loading` attribute, I need to show a different html element. How can I check if image is loaded?

**Comment by pinalto** [comment]
@rocchidavide How about this?
```html
  <img v-lazy="xxxx.jpg">
  <span class="loading">
    Loading
  </span>
```
```css
img:not([lazy='loading']) + .loading {
  display: none;
}
```
