### ISSUE TITLE
Simple fade animation between loader and image

### ISSUE THREAD

**Issue by lbineau** [hilongjw/vue-lazyload#82]
Thank you to contribute to VueJS plugin ecosystem.
I wonder if it is possible to have a simple transition on the image. 
I guess that for now you replace the img src attribute so no transition is possible.
Is there an easy way to achieve that ?

Otherwise what do you think about implementing the transition system of Vue?

**Comment by hilongjw** [comment]
I'm not sure can do this through Vue's transition system.

you can refer this demo page, use css animation with element attribute [http://hilongjw.github.io/vue-lazyload/](http://hilongjw.github.io/vue-lazyload/)
```css
img[lazy=loaded] {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
  -webkit-animation-name: fadeIn;
  animation-name: fadeIn;
}
```
