### ISSUE TITLE
Fade broken

### ISSUE THREAD

**Issue by lbineau** [hilongjw/vue-lazyload#99]
The transition behavior seems to be broken.
Worked for sure on version 0.9.5
Do not work with current version 1.0.0-rc7
Anyone experience the same issue.

```scss
/*
* Lazy loading
*/
img{
  transition: opacity 1s;
  &[lazy=loading]{
    opacity: 0;
    visibility: hidden;
  }
  &[lazy=loaded]{
    opacity: 1;
    visibility: visible;
  }
}
```
